### ISSUE TITLE
Add Proxy Support

### ISSUE THREAD

**Issue by huluxiaohuowa** [oliversen/chatgpt-docstrings#8]
![WechatIMG1329](https://github.com/user-attachments/assets/aa8ba3b6-e15f-48cf-997e-5fc4d89640a7)
<img width="1091" alt="image" src="https://github.com/user-attachments/assets/cc064da8-91fc-4224-b9c0-a94419491926">

The network environment in mainland China requires the use of a proxy, but it seems this plugin does not utilize the proxy settings of VS Code.

**Comment by oliversen** [comment]
It will be fixed soon. Thank you!

**Comment by oliversen** [comment]
As of version 0.9.1, the extension supports proxy. Proxy can be set at the extension level with the `chatgpt-docstrings.proxy` setting or at the vscode level (`http.proxy`). The `http_proxy` and `https_proxy` environment variables are also inherited.
